CREATE TABLE `categories` (
   `id` VARCHAR(255) PRIMARY KEY ,
   `name` VARCHAR(255) NOT NULL,
   `parent` VARCHAR(255) NULL,
   `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   FOREIGN KEY (parent) REFERENCES categories(id) ON DELETE CASCADE ON UPDATE CASCADE
);
