CREATE TABLE `courses` (
   `id` int(10) AUTO_INCREMENT PRIMARY KEY,
   `course_id` VARCHAR(255) UNIQUE ,
   `title` VARCHAR(255) NOT NULL,
   `description` text NOT NULL,
   `image_preview` VARCHAR(255) NOT NULL,
   `category_id` VARCHAR(255) NOT NULL,
   `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE ON UPDATE CASCADE
);
